mjpeg_encoder: fix bool vs. boolean mismatch
Fixes:

  .../libcamera-apps-b1ca8997530f1f0290b291a956de359f2d4ce3e2/mjpeg_encoder.cpp:57:22: error: cannot convert ‘bool’ to ‘boolean’ in assignment
     57 |  cinfo.raw_data_in = true;
        |                      ^~~~
  compilation terminated due to -Wfatal-errors.

Signed-off-by: Peter Seiderer <ps.report@gmx.net>