mjpeg_encoder: fix long unsigned int vs. size_t mismatch
Introduce a custom jpeg_mem_len_t as the jpeg_mem_dest() signature
changed since jpegsrc.v9d from 'unsigned long * outsize' to
'size_t * outsize'.

Fixes:

  .../libcamera-apps-b1ca8997530f1f0290b291a956de359f2d4ce3e2/mjpeg_encoder.cpp:61:44: error: invalid conversion from ‘long unsigned int*’ to ‘size_t*’ {aka ‘unsigned int*’} [-fpermissive]
     61 |     jpeg_mem_dest(&cinfo, &encoded_buffer, &buffer_len);
        |                                            ^~~~~~~~~~~
        |                                            |
        |                                            long unsigned int*

Signed-off-by: Peter Seiderer <ps.report@gmx.net>